### ISSUE TITLE
error:Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

### ISSUE THREAD

**Issue by hanling6889580** [PiotrSobczak/speech-emotion-recognition#12]
The following error occurred when I ran the run_training_ensemble.py .
How to solve it？

l.torch -l saved_models/linguistic_0.401Acc_0.346UAcc_2020-01-02_09:49:58/linguistic_model.torch
create_embedding - 2.428551197052002 sec
Dataset loaded.
load_spectrogram_dataset - 0.7873547077178955 sec
Dataset loaded.
load_linguistic_dataset - 0.5902986526489258 sec
Failed to load model from saved_models/acoustic_spec_0.539Acc_0.556UAcc_2020-01-07_08:49:38/acoustic_spec_model.torch without device mapping. Trying to load with mapping to cuda
Failed to load model from saved_models/linguistic_0.401Acc_0.346UAcc_2020-01-02_09:49:58/linguistic_model.torch without device mapping. Trying to load with mapping to cuda
Traceback (most recent call last):
  File "run_training_ensemble.py", line 48, in <module>
    train(model, ensemble_cfg, test_iterator, train_iterator, validation_iterator)
  File "/home/hl/Desktop/speech-emotion-recognition-master/speech_emotion_recognition/train.py", line 41, in train
    val_loss, val_cm = run_epoch_eval(model, validation_iterator, criterion)
  File "/home/hl/Desktop/speech-emotion-recognition-master/speech_emotion_recognition/model_utils.py", line 48, in run_epoch_eval
    predictions = model(batch)
  File "/home/hl/anaconda/ll/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hl/Desktop/speech-emotion-recognition-master/speech_emotion_recognition/models.py", line 130, in forward
    acoustic_output_features = self.acoustic_model.extract(acoustic_features)
  File "/home/hl/Desktop/speech-emotion-recognition-master/speech_emotion_recognition/models.py", line 104, in extract
    x = self.conv_layers(x)
  File "/home/hl/anaconda/ll/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hl/anaconda/ll/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/hl/anaconda/ll/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hl/anaconda/ll/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/hl/anaconda/ll/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

**Comment by PiotrSobczak** [comment]
This occurs when you are trying to feed a tensor optimized for GPU(torch.cuda.FloatTensor) to a model which has weights of CPU type. Try doing model.cuda() on your network if you want to utilize GPU or do input_tensor.to('cpu')

**Comment by hanling6889580** [comment]
at first i have trained  linguistic_model and acoustic-spectrogram_model on cuda.
and then 
i have alter "model.cuda()"  in run_training_ensemble.py.
code just like this.
####
 """Converting model to specified hardware and format"""
    acoustic_cfg_json = json.load(open(args.acoustic_model.replace(".torch", ".json"), "r"))
    acoustic_cfg = AcousticSpectrogramConfig(**acoustic_cfg_json)
    acoustic_model = CNN(acoustic_cfg)
    acoustic_model = acoustic_model.cuda()
    acoustic_model.load(args.acoustic_model)
    print(args.acoustic_model+" has loaded")
    

    linguistic_cfg_json = json.load(open(args.linguistic_model.replace(".torch", ".json"), "r"))
    linguistic_cfg = LinguisticConfig(**linguistic_cfg_json)
    linguistic_model = AttentionLSTM(linguistic_cfg)
    linguistic_model = linguistic_model.cuda()
    linguistic_model.load(args.linguistic_model)
    print(args.linguistic_model + " has loaded")
###

But
when i run  run_training_ensemble again ,  i got this error.

###
Failed to load model from saved_models/acoustic_spec_0.542Acc_0.569UAcc_2020-01-08_09:57:14/acoustic_spec_model.torch without device mapping. Trying to load with mapping to cuda
saved_models/acoustic_spec_0.542Acc_0.569UAcc_2020-01-08_09:57:14/acoustic_spec_model.torch has loaded
Failed to load model from saved_models/linguistic_0.373Acc_0.344UAcc_2020-01-08_10:08:18/linguistic_model.torch without device mapping. Trying to load with mapping to cuda
saved_models/linguistic_0.373Acc_0.344UAcc_2020-01-08_10:08:18/linguistic_model.torch has loaded
Traceback (most recent call last):
  File "run_training_ensemble.py", line 53, in <module>
    train(model, ensemble_cfg, test_iterator, train_iterator, validation_iterator)
  File "/home/hl/Desktop/speech-emotion-recognition-master/speech_emotion_recognition/train.py", line 41, in train
    val_loss, val_cm = run_epoch_eval(model, validation_iterator, criterion)
  File "/home/hl/Desktop/speech-emotion-recognition-master/speech_emotion_recognition/model_utils.py", line 48, in run_epoch_eval
    predictions = model(batch)
  File "/home/hl/anaconda/ll/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hl/Desktop/speech-emotion-recognition-master/speech_emotion_recognition/models.py", line 133, in forward
    return self.fc(self.dropout(all_features))
  File "/home/hl/anaconda/ll/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hl/anaconda/ll/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/hl/anaconda/ll/lib/python3.7/site-packages/torch/nn/functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_addmm

**Comment by hanling6889580** [comment]
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

**Comment by hanling6889580** [comment]
I solved the problem according to your guidance。


Add a line of code here。


ensemble_cfg = EnsembleConfig(acoustic_cfg, linguistic_cfg)
    model = FeatureEnsemble(ensemble_cfg, acoustic_model, linguistic_model)
    model = model.cuda(device)

    train(model, ensemble_cfg, test_iterator, train_iterator, validation_iterator)

**Comment by PiotrSobczak** [comment]
That's great. I will try to create a PR with fixes this month. I'm closing the issue for now. :)
