### ISSUE TITLE
Update recipe for linguistic model

### ISSUE THREAD

**Issue by pbrusco** [PiotrSobczak/speech-emotion-recognition#15]
Hi, 

Please update the readme and sourcecode for training the linguistic model. 

I assumed I had to go inside the data_loader and execute `generate_transcriptions` . Also, I had to download the deepspeech models after I figure out I need them, ~~also I think the deepspeech_generator is deprecated, so I had to make a sys call~~
         

Thanks again!

**Comment by pbrusco** [comment]
I found out that the "deep_generator" was a script on the speech_emotion_recognition folder. My bad. Anyway the steps for generating the linguistic models will be appreciated :). Thanks again. 

Managed generate ASR transcriptions run it by running:

`$ python`
`import speech_emotion_recognition.data_loader as dl`
`from speech_emotion_recognition import *`
`dl.generate_transcriptions()`

**Comment by leijue222** [comment]
I hava download deepspeech [model](https://github.com/mozilla/DeepSpeech/releases/download/v0.5.1/deepspeech-0.5.1-models.tar.gz).

`Deepspeech 0.5.1` must use ubuntu. Then the `generate_transcriptions()` will be worked .

But a new problem is here: 
How to get the file of `embeddings_array.numpy` and` word_to_index.pickle`?

https://github.com/PiotrSobczak/speech-emotion-recognition/blob/8ecbcf11a6dbc6d6802e51f7f797fcd85fdb7992/speech_emotion_recognition/word2vec_wrapper.py#L14-L15
@PiotrSobczak

**Comment by leijue222** [comment]
I hava download deepspeech [model](https://github.com/mozilla/DeepSpeech/releases/download/v0.4.1/deepspeech-0.4.1-models.tar.gz).
But the requirements.txt version of deepspeech is wrong and I can't run `data_loader.generate_transcriptions()`
```
ERROR: Could not find a version that satisfies the requirement deepspeech==0.5.1 (from versions: 0.5.0a5, 0.5.0a6, 0.5.0a7, 0.5.0a8, 0.6.0a5, 0.6.0a6, 0.6.0a7, 0.6.0a8, 0.6.0a9, 0.6.0a10, 0.6.0a11, 0.6.0a12, 
0.6.0a13, 0.6.0a14, 0.6.0a15, 0.6.0, 0.6.1a0, 0.6.1, 0.7.0a0, 0.7.0a1, 0.7.0a2, 0.7.0a3, 0.7.0a4, 0.7.0, 0.7.1a0, 0.7.1a1, 0.7.1a2, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.8.0a0, 0.8.0a1, 0.8.0a2, 0.8.0a3, 0.8.0a4, 0.8.0a5, 0.8.0a6, 0.8.0a7, 0.8.0a8, 0.8.0, 0.8.1, 0.8.2, 0.9.0a0, 0.9.0a1, 0.9.0a2, 0.9.0a3, 0.9.0a8, 0.9.0a9, 0.9.0a10, 0.9.0a11, 0.9.0a12, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0a3)
ERROR: No matching distribution found for deepspeech==0.5.1
```
If I use version <= 0.6.1, the error is:
```
Traceback (most recent call last):
  File "data_loader.py", line 242, in <module>
    generate_transcriptions()
  File "data_loader.py", line 227, in generate_transcriptions
    transcription = speech_to_text("models/output_graph.pbmm", "models/alphabet.txt", "models/lm.binary", "models/trie", abs_path)
  File "E:\project\Emotion\speech-emotion-recognition-master\speech_emotion_recognition\deepspeech_generator.py", line 74, in speech_to_text
    Models.ds = Model(model, N_FEATURES, N_CONTEXT, alphabet, BEAM_WIDTH)
  File "D:\software\anaconda3\envs\torch0.4\lib\site-packages\deepspeech\__init__.py", line 40, in __init__
    status, impl = deepspeech.impl.CreateModel(*args, **kwargs)
TypeError: CreateModel() takes at most 2 arguments (5 given)
```
else the error is:
```
Traceback (most recent call last):
  File "data_loader.py", line 242, in <module>
    generate_transcriptions()
  File "data_loader.py", line 218, in generate_transcriptions
    from deepspeech_generator import speech_to_text
  File "E:\project\Emotion\speech-emotion-recognition-master\speech_emotion_recognition\deepspeech_generator.py", line 13, in <module>
    from deepspeech import Model, printVersions
ImportError: cannot import name 'printVersions'
```

@PiotrSobczak @pbrusco 
How can  I run `generate_transcriptions()`?

**Comment by leijue222** [comment]
@PiotrSobczak 
:sob: I have no any way to get `embeddings_array.numpy` and `word_to_index.pickle`.
Can you give me some instructions?

**Comment by cui0721** [comment]
Hello, I would like to ask where to generate the NPY file

**Comment by ADOLoooo** [comment]
the same question about how to generate embeddings_array.numpy and word_to_index.pickle。。。Thanks
